import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Resolution from "@lestprotocol/sdk"
import { useEffect, useState } from 'react';


function formatNumber(num: number): string {
  if (num >= 1000000) {
    return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'M';
  } else if (num >= 1000) {
    return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K';
  }
  return num.toString();
}


const Home: NextPage = () => {

  const [name, setName] = useState("")
  const [address, setAddress] = useState("")
  const [balance, setBalance] = useState({} as {
    formatted: string;
    value: bigint;
  })
  const [loading, setLoading] = useState(false)
  const resolve = () => {
    const resolution = new Resolution()
    setLoading(true)
    resolution.resolveDomain(name).then(data => {
      setLoading(false)
      setAddress(data.address)
      setBalance((data.balance))
    }).catch(e=> console.log(e))
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <div style={{
          marginTop: "10px"
        }}>
          <input type="text" value={name} onChange={(e) => setName(e.target.value)} />
          <button onClick={resolve}>{loading? "Loading.....":"Resolve your name"}</button>
          <h1>{name}</h1>
          <p>Address: {loading ? "Loading...." : address}</p>
          <p>Balance: {loading ? "Loading...." : formatNumber(Number(balance.formatted))}</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
